services:
  locator-service:
    build:
      context: ./locator-service
      dockerfile: Dockerfile
    image: locator-service
    ports:
      - 8080:8080
    command: node index.js
    environment:
      - TRIMET_API_KEY=${TRIMET_API_KEY}
    links:
      - redis
    restart: unless-stopped

  locator-client:
    build:
      context: ./locator-client
      dockerfile: Dockerfile
    image: locator-client
    ports:
      - 3000:3000
    command: node app.js
    links:
      - redis
      - locator-service
    restart: unless-stopped

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: unless-stopped
