version: '3'
services:
  locator-service:
    build:
      context: ./locator-service
      dockerfile: Dockerfile
    image: locator-service
    ports:
      - 8080:8080
    volumes:
      - ./locator-service:/app/locator-service
    links:
      - redis
    networks:
      - locator-network

  locator-client:
    build:
      context: ./locator-client
      dockerfile: Dockerfile
    image: locator-client
    ports:
      - 3000:3000
    volumes:
      - ./locator-client:/app/locator-client
    links:
      - redis
      - locator-service

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - locator-network

networks:
  locator-network:
