version: '3'
services:
  locator:
    build:
      context: ./locator-service
      dockerfile: Dockerfile
    image: locator-service
    ports: 
      - 4040:80
    volumes:
      - ./locator-service:/app/locator-service
    links: 
      - redis
  
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    